syntax = "proto3";

package main_element;

message MainElement {
  string title = 1;
  repeated ActionButton action_buttons = 2;

  oneof content {
    StaticPage static_page = 16;
    SimpleTable simple_table = 17;
    AdvancedTable advanced_table = 18;
  }
}

message StaticPage {
  string title = 1;
  repeated StaticPageElement elements = 2;
}

message StaticPageElement {
  oneof content {
    Paragraph paragraph = 1;
    List list = 2;
    SimpleTable simple_table = 3;
    CodeBlock code_block = 4;
  }
}

message Paragraph {
  repeated TextSpan text_spans = 1;
}

message TextSpan {
  string text = 1;
  TextSpanStyle style = 2;
}

message TextSpanStyle {
  string color = 1;
  bool bold = 2;
  bool italic = 3;
}

message List {
  repeated ListItem items = 1;
}

message ListItem {
  int32 level = 1;
  repeated TextSpan text_spans = 2;
}

message CodeBlock {
  repeated TextSpan text_spans = 1;
  string language = 2;
}

message SimpleTable {
  repeated SimpleTableRow rows = 1;
}

enum TableRowStyle {
  TABLE_ROW_STYLE_UNSPECIFIED = 0;
  TABLE_ROW_STYLE_HEADER = 1;
  TABLE_ROW_STYLE_DATA = 2;
}

message SimpleTableRow {
  TableRowStyle style = 1;
  repeated SimpleTableCell cells = 2;
}

message SimpleTableCell {
  repeated TextSpan text_spans = 1;
}

message AdvancedTable {
  string url = 1;
  repeated AdvancedTableColumn columns = 2;
  repeated AdvancedTableRow rows = 3;
  bool table_filterable = 4;
}

message AdvancedTableColumn {
  string id = 1;
  string title = 2;
  string description = 3;
  ColumnType type = 4;
  bool sortable = 5;
  bool searchable = 6;
  bool filterable = 7;
  repeated TableCellValue possible_values = 8; // used by enums and filterable columns (not enforced by filterable columns)
  uint32 decimal_digits = 9; // only applicable for decimal and floating point values
  string unit = 10;
  RangeFilter range_filterable = 11;
  uint32 column = 12; // if absent, the column is not included in the table
  SortDirection sort_direction = 13;
}

enum ColumnType {
  COLUMN_TYPE_UNSPECIFIED = 0;
  COLUMN_TYPE_STRING = 1;
  COLUMN_TYPE_INT = 2;
  COLUMN_TYPE_DECIMAL = 3;
  COLUMN_TYPE_FLOAT = 4;
  COLUMN_TYPE_DOUBLE = 5;
  COLUMN_TYPE_DATE = 6;
  COLUMN_TYPE_TIME = 7;
  COLUMN_TYPE_DATETIME = 8;
  COLUMN_TYPE_BOOLEAN = 9;
  COLUMN_TYPE_ENUM = 10;
}

message RangeFilter {
  TableCellValue min = 1;
  TableCellValue max = 2;
}

message AdvancedTableRequest {
  repeated AdvancedTableRequestColumn columns = 1;
  string search = 2;
  uint32 offset = 3;
  uint32 limit = 4;
}

message AdvancedTableRequestColumn {
  string id = 1;
  string search = 2;
  TableCellValue filter = 3;
  uint32 sort_index = 4;
  SortDirection sort_direction = 5;
}

enum SortDirection {
  SORT_DIRECTION_UNSPECIFIED = 0;
  SORT_DIRECTION_ASC = 1;
  SORT_DIRECTION_DESC = 2;
}

message AdvancedTableRow {
  repeated TableCellValue cells = 1;
  repeated ActionButton action_buttons = 2;
}

message TableCellValue {
  oneof value {
    string string_value = 1;
    int32 int_value = 2;
    double double_value = 3;
    float float_value = 4;
    bool boolean_value = 5;
  }
}

message ActionButton {
  string label = 1;
  string icon = 2; // iconset:icon-name (far/fas/fal for font awesome regular/solid/light)
  oneof action {
    GoToUrlAction go_to_url = 8;
    OpenPageAction open_page = 9;
    OpenModalAction open_modal = 10;
  }
}

message GoToUrlAction {
  string url = 1;
}

message OpenPageAction {
  string url = 1;
}

message OpenModalAction {
  string url = 1;
}
